### ISSUE TITLE
Conflict with Recents tweak.

### ISSUE THREAD

**Issue by prathumca** [r-plus/PullBulletin#1]
Hi,

I'm the author of Recents and would like to bring your attention that 'PullBulletIn' is showing pull to clear option on Recents screen, but it should not.

I can fix it if you give me access to PullBulletIn repo.

Thanks,

**Comment by prathumca** [comment]
This what I suggest to support any tweaks that don't want to show 'PullBulletIn' in their view.

@interface SBBulletinViewController : UIViewController
@property(nonatomic, assign) id delegate;
@end

@interface SBBulletinObserverViewController
...
- (BOOL)canShowPullToRefresh; //This should be added in their implementation as below

/**
%new
- (BOOL)canShowPullToRefresh {
  return YES;
  }
  */
  @end

And finally 

%hook SBBulletinViewController
- (void)viewDidLoad
  {
  .....
  if (![self isMemberOfClass:%c(SBBulletinViewController)] || ([[self delegate] respondsToSelector:@selector(canShowPullToRefresh)] && ![[self delegate] canShowPullToRefresh])) {
      return;
  }
  ......
  }
  %end

**Comment by r-plus** [comment]
Okey, Could you give me a pull request?

**Comment by prathumca** [comment]
I could not able to do it, since I have no permissions to create a branch.

**Comment by prathumca** [comment]
Or create a separate branch, I'll give a try it on.

**Comment by r-plus** [comment]
Do you know github pull request feature? Not require repository push able permission for pull request. 
Fork -> commit -> push then send pull request from web.

**Comment by prathumca** [comment]
Done. Please add review and see what can be done from your side.

**Comment by r-plus** [comment]
Thanks!
This is new build deb package, make sure. http://cl.ly/bB74
If you ok, I'll submit this version to repository.

**Comment by prathumca** [comment]
Works good on my device. You can also give a try with Recents (it has a free trial).

**Comment by r-plus** [comment]
Okey submitted.
Thanks for your work.
